export const productData = [
  {
    id: "pipe-inspection-robot",
    name: "Pipe Inspection Robot",
    slug: "pipe-inspection-robot",
    products: [
      {
        id: "amphibious-robot-s450a",
        title: "Amphibious Robot S450A",
        slug: "amphibious-robot-s450a",
        category: "Pipe Inspection Robot",
        categorySlug: "pipe-inspection-robot",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2F295a24dab7a21c783a6eb11cf3ec2968.webp",
        description: [
          "The crawler system is equipped with a waterproof spiral-shaped float which is suitable for sludge-covered and submerged sewers. The 360 degree pan and tilt camera with a sonar to inspect sewers completely.",
        ],
      },
      {
        id: "s300e-pipe-inspection-robot",
        title: "S300E Pipe Inspection Robot",
        slug: "s300e-pipe-inspection-robot",
        category: "Pipe Inspection Robot",
        categorySlug: "pipe-inspection-robot",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2Fcf640ef14b78a16da0b96db67b530a67.webp",
        description: [
          "● Interchangeable HD Pan Tilt Zoom Camera Head",
          "● 6 Wheels Steerable Drive System",
          "● To Inspect Pipes from 300-2000mm (12\" -80'') Diameter",
          "● With motorized lift",
          "● WinCan Compatible",
        ],
      },
      {
        id: "s200c-pipe-inspection-robot",
        title: "S200C Pipe Inspection Robot",
        slug: "s200c-pipe-inspection-robot",
        category: "Pipe Inspection Robot",
        categorySlug: "pipe-inspection-robot",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2F8ecf94204b3ba8c8076447a7006d683d.webp",
        description: [
          "● Interchangeable HD Pan Tilt Zoom Camera Head",
          "● 6 Wheels Steerable Drive System",
          "● To Inspect Pipes from 200-1000mm (8'' -40'') Diameter",
          "● With motorized lift",
          "● WinCan Compatible",
        ],
      },
      {
        id: "s100-pipe-inspection-robot",
        title: "S100 Pipe Inspection Robot",
        slug: "s100-pipe-inspection-robot",
        category: "Pipe Inspection Robot",
        categorySlug: "pipe-inspection-robot",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2F1e3941aa37b37771ef730efaeef25576.webp",
        description: [
          "● Interchangeable Pan-and-Tilt Camera Head",
          "● 6 Wheels Steerable Drive System",
          "● To Inspect Pipes from 4'' to 20'' Diameter",
          "● High Powered Built-in LEDs for Excellent Illumination",
        ],
      },
    ],
  },
  {
    id: "push-camera",
    name: "Push Camera",
    slug: "push-camera",
    products: [
      {
        id: "p14-push-rod-camera",
        title: "P14 Push Rod Camera",
        slug: "p14-push-rod-camera",
        category: "Push Camera",
        categorySlug: "push-camera",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2F78c07a22cb01ac5a1d8290562b78e791.webp",
        description: [
          "● Unique, professional and compact design",
          "● The cable reel is out of the box, easy to clean and won't cause dirty in the box.",
          "● Easy to carry; convenient transportation.",
          "● Comes with a smart braking system.",
        ],
      },
      {
        id: "p23-push-rod-camera",
        title: "P23 Push Rod Camera",
        slug: "p23-push-rod-camera",
        category: "Push Camera",
        categorySlug: "push-camera",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2F805eacfedde34ef696ff5453bd1f0513.webp",
        description: [
          "● Unique, professional and compact design",
          "● The cable reel is out of the box, easy to clean and won't cause dirty in the box.",
          "● Easy to carry; convenient transportation.",
          "● Comes with a smart braking system.",
        ],
      },
      {
        id: "p40a-push-rod-camera",
        title: "P40A Push Rod Camera",
        slug: "p40a-push-rod-camera",
        category: "Push Camera",
        categorySlug: "push-camera",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2Fc466eb8d3d7ae81a9714075a30efdaa3.webp",
        description: [
          "● With 38mm auto-leveling camera head",
          "● With high brightness Leds for better viewing",
          "● Easy to carry, convenient transportation.",
          "● Comes with a smart braking system.",
        ],
      },
      {
        id: "p40b-push-camera",
        title: "P40B Push Camera",
        slug: "p40b-push-camera",
        category: "Push Camera",
        categorySlug: "push-camera",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2F19c6a1880be1f6579ffbb49f17489990.webp",
        description: [
          "● With 38mm auto-leveling camera head",
          "● With high brightness Leds for better viewing",
          "● Easy to carry, convenient transportation.",
          "● Comes with a smart braking system.",
        ],
      },
      {
        id: "p40c-push-camera",
        title: "P40C Push Camera",
        slug: "p40c-push-camera",
        category: "Push Camera",
        categorySlug: "push-camera",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2Ff4cae43e4743bdfdbe80ec7913980ea6.webp",
        description: [
          "● With 38mm auto-leveling camera head",
          "● With high brightness Leds for better viewing",
          "● Easy to carry, convenient transportation.",
          "● Comes with a smart braking system.",
        ],
      },
      {
        id: "p40d-push-camera",
        title: "P40D Push Camera",
        slug: "p40d-push-camera",
        category: "Push Camera",
        categorySlug: "push-camera",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2Fb49ca1c678272c51a4ac6a7ea297c8b6.webp",
        description: [
          "● With 38mm auto-leveling camera head",
          "● With high brightness Leds for better viewing",
          "● Easy to carry, convenient transportation.",
          "● Comes with a smart braking system.",
        ],
      },
      {
        id: "p50-pan-tilt-push-rod-camera",
        title: "P50 Pan Tilt Push Rod Camera",
        slug: "p50-pan-tilt-push-rod-camera",
        category: "Push Camera",
        categorySlug: "push-camera",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2F6e9d2d044db526d97761f84b811811ca.webp",
        description: [
          "● ø50mm Pan & Tilt 1080p Full HD camera head",
          "● 7'' Android Touch screen with joystick which is more convenient to operate",
          "● Soft keyboard with Google input",
          "● With HDMI and hot spot to display the video in external screen.",
        ],
      },
    ],
  },
  {
    id: "manhole-camera",
    name: "Manhole Camera",
    slug: "manhole-camera",
    products: [
      {
        id: "e25-hd-wireless-manhole-camera",
        title: "E25 HD Wireless Manhole Camera",
        slug: "e25-hd-wireless-manhole-camera",
        category: "Manhole Camera",
        categorySlug: "manhole-camera",
        imageUrl: "https://dedjh0j7jhutx.cloudfront.net/1592130268741804032%2F943970aa877859c2189d1f7d20100f40.webp",
        description: [
          "● With high resolution camera module",
          "● 25 ×optical zoom optional",
          "● 10'' wireless control tablet",
          "● 7/9/12m telescopic pole optional",
        ],
      },
    ],
  },
  {
    id: "videoscope",
    name: "Videoscope",
    slug: "videoscope",
    products: [
      {
        id: "srod-sd6-series-videoscope",
        title: "SROD SD6 Series Videoscope",
        slug: "srod-sd6-series-videoscope",
        category: "Videoscope",
        categorySlug: "videoscope",
        imageUrl: "https://dedjh0j7jhutx.cloudfront.net/1592130268741804032%2Fb179ec00f7c796698195dde96d939875.webp",
        description: [
          "● 1080P Ultra Definition Image",
          "● Replaceable Monitor",
          "● Optional Tube Diameter",
          "● 360° Accurate Articulation With Joystick",
          "● 8h Continuous Working Time",
        ],
      },
    ],
  },
  {
    id: "cutter",
    name: "Cutter",
    slug: "cutter",
    products: [
      {
        id: "turbo-4",
        title: "TURBO 4",
        slug: "turbo-4",
        category: "Cutter",
        categorySlug: "cutter",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2Fc4fc8354067939aeb1dd3e1681b6ddfb.webp",
        description: [
          "With the TURBO 4 main sewer cutting robot, you can easily work in main sewers with nominal diameters between DN200 and DN800. The rehabilitation components make the device multifunctional.",
        ],
      },
      {
        id: "turbo-3",
        title: "TURBO 3",
        slug: "turbo-3",
        category: "Cutter",
        categorySlug: "cutter",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2F3de047f80e8bc312ae06ae9765f0d682.webp",
        description: [
          "Proven cutting technology for the main sewer Cutting work in main sewers with nominal diameter between DN200 to DN600 can be carried out effectively with the TURBO3 cutter utilising its powerful air motor.",
        ],
      },
      {
        id: "drive-plus",
        title: "DRIVE PLUS",
        slug: "drive-plus",
        category: "Cutter",
        categorySlug: "cutter",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2Fd46f34f1d5af1a3a3578cd7c88941fde.webp",
        description: [
          "● For small and main sewer from DN 150-400 / 6''-16''",
          "● 2 exchangeable air-operated cutter motors",
          "● 100 m / 328 ft and 150 m / 492 ft supply hose",
        ],
      },
      {
        id: "drive-4",
        title: "DRIVE 4",
        slug: "drive-4",
        category: "Cutter",
        categorySlug: "cutter",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2F9e94500c95f2a86583c94ea6c5ee91e9.webp",
        description: [
          "The drive 4 is cutting works in small and medium-sized main sewers flexible applicable. The main sewer robot can be used from DN150 to DN400 and is equipped with power air motor.",
        ],
      },
    ],
  },
  {
    id: "uv",
    name: "UV",
    slug: "uv",
    products: [
      {
        id: "uv8000-light",
        title: "UV8000 Light",
        slug: "uv8000-light",
        category: "UV",
        categorySlug: "uv",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2F6399b137b49040fdc28e42ab15b10b78.webp",
        description: [
          "Coming with a total curing power of 8000 watts. A cable length of up to 210 meters and at a very competitive price level. The new UV8000 light can be considered the idea starter solution for the main line light curing.",
        ],
      },
      {
        id: "uv8000-compact",
        title: "UV8000 Compact",
        slug: "uv8000-compact",
        category: "UV",
        categorySlug: "uv",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2Fe2d58be7e21221ec5b3696658563d13e.webp",
        description: [
          "UV curing for medium and large main sewers Lengthy construction sites for trench-less rehabilitation of main sewers are a thing of the past. With the UV curing system from IMS robots, you can rehabilitate medium and large main sewers quickly and sustainably.",
        ],
      },
      {
        id: "uv12000",
        title: "UV12000",
        slug: "uv12000",
        category: "UV",
        categorySlug: "uv",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2Fac1559ced2e32e29af0bb5ee597e0a77.webp",
        description: [
          "UV curing for liners up to DN1600 Trench-less rehabilitation of large main sewers poses challenges for man and technology. With the UV12000 Compact you can cure liners up to DN1600- with different light sources.",
        ],
      },
      {
        id: "uv7800",
        title: "UV7800",
        slug: "uv7800",
        category: "UV",
        categorySlug: "uv",
        imageUrl: "https://d1c6gk3tn6ydje.cloudfront.net/1592130268741804032%2F06e83bcc31d2cc47cb215d4c97e5cc89.webp",
        description: [
          '● Light source from DN 150/6"',
          "● Software, machine control, measurement data acquisition and evaluation",
          "● Industrial control with touch panel",
          "● For 180 m/590 ft curing cable",
        ],
      },
    ],
  },
]
